version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopping
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis-stack:
    image: redis/redis-stack-server
    ports:
      - 6379:6379
      - 8001:8001

volumes:
  pg_data:

