version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopping
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis-stack:
    image: redis/redis-stack-server
    ports:
      - 6379:6379
      - 8001:8001

  zookeeper:
    image: zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog  

  kafka:
    image: confluentinc/cp-kafka:5.4.9
    hostname: kafka
    ports:
     - 9091:9091
    environment:
     - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://kafka:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
     - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_BROKER_ID=1
     - KAFKA_LOG4J_LOGGERS=kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
    volumes:
      - kafka-data:/var/lib/kafka/data 
    depends_on:
      - zookeeper 


  jdbc-connect:
    image: debezium/connect-jdbc-es:1.9
    container_name: hellojob_kafka_connector
    build:
      context: debezium-jdbc-es
      args:
        DEBEZIUM_VERSION: 1.9
    networks:
      - hellojob-network    
    ports:
     - 8083:8083
     - 5005:5005
    environment:
     - BOOTSTRAP_SERVERS=kafka1:19091,kafka2:19092,kafka3:19093
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      ELASTIC_PASSWORD: 'uiop7890'
      discovery.type: 'single-node'
      bootstrap.memory_lock: true
      xpack.security.http.ssl.enabled: false
      xpack.license.self_generated.type: 'basic'
    # this return code 137
    # mem_limit: 2048m 
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.6
    volumes:
      - kibana-config:/usr/share/kibana/config/
      - kibana-data:/usr/share/kibana/data  
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200  
    ports:
      - 5601:5601  


volumes:
  pg_data:
  es_data:
  zookeeper-data:
  zookeeper-datalog:
  kafka-data:
  kibana-config:
  kibana-data:
