version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopping
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis-stack:
    image: redis/redis-stack-server
    ports:
      - 6379:6379
      - 8001:8001

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      ELASTIC_PASSWORD: 'uiop7890'
      discovery.type: 'single-node'
      bootstrap.memory_lock: true
      xpack.security.http.ssl.enabled: false
      xpack.license.self_generated.type: 'basic'
    # this return code 137
    # mem_limit: 2048m 
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  pg_data:
  es_data:

